### ISSUE TITLE
Possible to see the encryption key

### ISSUE THREAD

**Issue by jopie282** [smrtprjcts/mijiatemp#12]
Hi in order to connect it to home assistant I need to find the encryption key. Do you have that key hidden in the data for the lywsd03mmc?

**Comment by nikito7** [comment]
I think he don't use it yet

**Comment by smrtprjcts** [comment]
> Hi in order to connect it to home assistant I need to find the encryption key. Do you have that key hidden in the data for the lywsd03mmc?

No, I don't have

**Comment by nikito7** [comment]
> Hi in order to connect it to home assistant I need to find the encryption key. Do you have that key hidden in the data for the lywsd03mmc?

https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#my-sensors-ble-advertisements-are-encrypted-how-can-i-get-the-key
