### ISSUE TITLE
Wrong database cleanup button

### ISSUE THREAD

**Issue by nepozs** [smrtprjcts/mijiatemp#14]
![Screenshot_2020-05-29-02-22-26](https://user-images.githubusercontent.com/56661567/83207540-bd639900-a153-11ea-8bda-32c280ed5b74.png)
It is "go to settings" instead of "yes"/"OK" or something similiar, and there is no reference to any translation string.

**Comment by smrtprjcts** [comment]
Thanks, i'll fix it

nepozs <notifications@github.com> ezt írta (időpont: 2020. máj. 29., P,
2:28):
