### ISSUE TITLE
no battery status display for rectangular epaper device LYWSD02

### ISSUE THREAD

**Issue by ThomasWaldmann** [smrtprjcts/mijiatemp#16]
battery status display of mijatemp for different device types:

- rectangular epaper with clock (Miaomiaoce, LYWSD02, HW F2_LN, FW 1.1.2_0038): does **not** work
- round epaper (Qingping Technology, CGG1, HW 0001, FW 1.1.2:0029): works
- small square lcd (Miaomiaoce, LYWSD03MMC, HW B1.4, FW 1.0.0_0106): works

is this a bug or limitation of mijatemp v2.2.6?

if so, could the battery status be implemented / fixed for the rectangular one somehow?

**Comment by ThomasWaldmann** [comment]
(and thanks for writing mijatemp, it's nice to have an app that doesn't need an online account or all sorts of permissions)

**Comment by ThomasWaldmann** [comment]
BTW, "does not work" means it displays the battery symbol with the question mark and no percentage value.

**Comment by smrtprjcts** [comment]
@ThomasWaldmann 
Sorry for the late answer. LYWSD02 cannot broadcast the battery level. But it can be read via connection. It's an option inside of the settings of the device.

**Comment by nikito7** [comment]
> @ThomasWaldmann
> Sorry for the late answer. LYWSD02 cannot broadcast the battery level. But it can be read via connection. It's an option inside of the settings of the device.

You need last firmware update (...0085)

Last firmware broadcast battery

Update with Mi Home

**Comment by smrtprjcts** [comment]
Thanks @nikito7. I have not known that. I've put it into the help

**Comment by ThomasWaldmann** [comment]
Interesting. Is there a method to update without "Mi Home"?
