### ISSUE TITLE
alternative payment / donation method?

### ISSUE THREAD

**Issue by ThomasWaldmann** [smrtprjcts/mijiatemp#17]
some people prefer to have their android devices without a google account / without google play store, google apps, google play services for better privacy.

that of course means there is no way to install the "pro" version from google play for them.
is there an alternative way?

alternatively, is there a way for a donation, like paypal or so?

**Comment by smrtprjcts** [comment]
Hi.

I made an aptoide version. It has different in-app payment. It is not tested yet, but should work.
These version has different name, ended with '-aptoide'.

https://mijiatemp.hu.aptoide.com/?store_name=catappult&app_id=53200397

**Comment by ThomasWaldmann** [comment]
I've installed aptoide, appcoin wallet and mijiatemp (via aptoide).

When clicking "store" and "pro version", it just says "in app billing not available".

**Comment by smrtprjcts** [comment]
I think you installed a Google Play version app from aptoide (these are fetched by aptoide from Play). The versionname should be ended with-aptoide.  Those are the aptoide ones, uploaded by me.
I uploaded the 2.2.7 for you about 5h ago but seems to be not available yet.

**Comment by ThomasWaldmann** [comment]
Ah, cool! Yeah, guess I got the wrong one and currently I only see an older 2.1.9-aptoide there. Thanks!

**Comment by smrtprjcts** [comment]
Great. Please give a feedback about the result. If not working I'd like to fix it.

**Comment by ThomasWaldmann** [comment]
Can confirm that the aptoide "donate appcoin credits" function works (at least AFAICS).

(and the appcoin credits can be "topped up" via paypal or credit card, so that answers my question)

**Comment by ThomasWaldmann** [comment]
I added aptoide to the README. Guess this is the minimum what's needed to close this issue. PR #19 

If you like, you could also explicitly talk about payment/donation options in the README.

**Comment by smrtprjcts** [comment]
Thank you very much, I've merged that!

**Comment by ThomasWaldmann** [comment]
Is there any news about a working, current `-aptoide` version?

There were quite some new google play releases (but I don't have play store nor google services), but no corresponding -aptoide release.

The animated advertisements in the recent releases are totally annoying, would like to get paid version.

**Comment by smrtprjcts** [comment]
Hi.
I uploaded the latest before uploaded to Play (avoid that Aptoide pulls the play version automatically from Play) (yes they do it and in this case i cannot upload the real aptoide version).
Maybe the string (-aptoide) was cut from the end by aptoide?
The version code of the latest 2.3.0
 - Play version: 2030000
 - Aptoide version: 2030050

Aptoide versions are always ended with 5x

As I see the correct version is on Aptoide

**Comment by ThomasWaldmann** [comment]
The aptoide store app shows version numbers like "2.3.0" (no fourth digit) and it still says I have the current version (I installed 2.3.0 a while ago but it has no working in-app purchases).

"Other versions" show 2.3.0 ... 2.2.1, 2.1.9-aptoide, 2.1.8-aptoide, 2.1.8, 2.1.5-aptoide, ...

**Comment by smrtprjcts** [comment]
I know. It's just a text
