### ISSUE TITLE
displays "please refresh the application"

### ISSUE THREAD

**Issue by ThomasWaldmann** [smrtprjcts/mijiatemp#18]
i tried to use 2.1.9-aptoide (latest one currently available, the 2.2.7-aptoide is not visible yet).

but, it only shows "please refresh the application" [EXIT] [OK] and no matter what one selects, it does not let one use the app.

is there some death switch in the app that disables it after some time / after some specific date?

or does it check if there are newer apps? in this case, there seems to be something wrong as there is no newer *-aptoide available.

**Comment by smrtprjcts** [comment]
2.2.7 is pending yet on Aptoide. Please be patient. I hope it's available soon

**Comment by ThomasWaldmann** [comment]
Hmm, how long is that "pending" usually? It's still not visible there.

**Comment by smrtprjcts** [comment]
I wrote a mail to aptoide support team yesterday about that. I have not any
answer yet.. I'm really sorry, I'm trying my best

TW <notifications@github.com> ezt írta (időpont: 2020. szept. 8., K 1:03):

**Comment by smrtprjcts** [comment]
Support is still dumb, if you want to get the apk, please drop a mail and
I'll send it

Smart Projects <smrtprjcts@gmail.com> ezt írta (időpont: 2020. szept. 8., K
8:35):

**Comment by ThomasWaldmann** [comment]
2.2.8 is now on google play and on aptoide, but no recent 2.2.x-aptoide (neither 2.2.7 nor 2.2.8).

**Comment by smrtprjcts** [comment]
They sent a mail to me half an hour ago. They fetched the play version app
from Google Play instead of the aptoide version I uploaded....
I don't know why but we are in conversion. It's slow..

TW <notifications@github.com> ezt írta (időpont: 2020. szept. 10., Cs,
13:45):

**Comment by ThomasWaldmann** [comment]
OK, thanks for caring for it. Hopefully they'll manage to distribute the aptoide version some day.

**Comment by smrtprjcts** [comment]
I have doubts so if you need the apk please drop a mail

TW <notifications@github.com> ezt írta (időpont: 2020. szept. 11., P,
17:15):

**Comment by ThomasWaldmann** [comment]
BTW, a while ago a "-aptoide" version got through, but it is already outdated again.

**Comment by smrtprjcts** [comment]
I uploaded the 2.5.0 a few days ago..
I wrote to the support yesterday..  no reply.. not a good service.

**Comment by smrtprjcts** [comment]
It's funny. I have just uploaded the 2.5.1 and it's alread available..

**Comment by ThomasWaldmann** [comment]
Yeah, I've installed that one meanwhile. Glad it worked!

**Comment by smrtprjcts** [comment]
Btw, they have not sent a reply yet...
