### ISSUE TITLE
improve german translation

### ISSUE THREAD

**Issue by ThomasWaldmann** [smrtprjcts/mijiatemp#20]
Overall it's quite good, but there are some minor issues:
- typos
- punctuation
- consistency, either always use Channel (keep all in English) or always use Kanal (transate to German).
- some other minor things

"foo bar" in English is often something like "Foo-Bar" in German (added hyphen).

Needs a proofread.

**Comment by ThomasWaldmann** [comment]
general question: are there places where string length is critical? german tends to be longer than english.

**Comment by ThomasWaldmann** [comment]
@j17z @chuelibrueder are you still working on the translation and could you fix these issues?

**Comment by smrtprjcts** [comment]
Hi,
I don't check the translations, some user translated the texts.
If you liked to fix anything, just do it and I'll merge that. Lenght
check would be too much work.. if someone finds any text is too long can
fix it here..

TW <notifications@github.com> ezt írta (időpont: 2020. szept. 6., V 21:25):

**Comment by j17z** [comment]
> @j17z @chuelibrueder are you still working on the translation and could you fix these issues?

Sorry, I am currently not available for the job.
