### ISSUE TITLE
make a homepage and docs site here?

### ISSUE THREAD

**Issue by ThomasWaldmann** [smrtprjcts/mijiatemp#21]
currently, the focus of this github repo is on translations mostly. but not only, there were also some non-translation issues in the issue tracker.

i noticed that there seems to be no easy to discover general "home page" of this app / project, there are just the app pages in the misc app stores where a feature description is visible.

instead of focussing on translations, the readme could be kind of the "elevator pitch" of this project and it could link to some github wiki pages with infos about translating, about misc. devices, a FAQ page, etc.?

just a suggestion.

**Comment by smrtprjcts** [comment]
@ThomasWaldmann the issues here is a mistake. This is only for translation. But could be more. But it's not so easy to make a good and useful FAQ/homepage. But if you have any useful missing info in the app I'd be glad if you shared with me :)
