### ISSUE TITLE
[Important] App is turned off after update issue

### ISSUE THREAD

**Issue by DOCHIS** [smrtprjcts/mijiatemp#22]
#15 To apply the merged Korean language, I deleted the app from the Play Store and reinstalled it.
However, as in the attached video, there is an issue that ends when the app is launched.

Video is provided along with information necessary for debugging.

# Video
https://vimeo.com/473404449

# Debug Info
App Version : 2.2.9

Phone Model : SM-N971N
One UI Version : 2.1
Android Version : 10

Video Date : 2020-10-29 PM 9:35 (UTC-9)

**Comment by smrtprjcts** [comment]
Hi!
Could you check that notification channel (TempService) is created ?
Somewhere in app settings (not in the app).

Have you tried to delete the data?

**Comment by DOCHIS** [comment]
-Delete app data
-Download from Play Store after deleting the app
I have tried the two methods above.
But it has not been resolved.

The suspicious content is shown in the image below.
![notibar](https://i.imgur.com/MPtKj7X.jpeg)

If you force the location authority to 'Always Allow' in the app settings,
the error 'location permit is required' is displayed as shown in the image above.

I'm guessing,
- Samsung's security clash with 'nox'
- Rights issues due to Android policy changes
- or conflicts with other apps installed on my phon

Thank you.

**Comment by smrtprjcts** [comment]
Hi.

It's working on another Samsung phones so seems to be a local issue.
Advice: delete the data. Uninstall the app. Wait an hour at least. Reboot the phone. Install again. Delete the data again. Start the app.
