### ISSUE TITLE
Chart contains only battery for ATC firmware / Mijia 2

### ISSUE THREAD

**Issue by bentolor** [smrtprjcts/mijiatemp#23]
In the chart diagram I can only see battery though temp & humidity are enabled.

I'm not sure: Is this by design for the non-Pro version or an issue due to the ATC firmware?

**Comment by smrtprjcts** [comment]
It's an issue with the custom firmware. I'll check it. Thanks for the report

**Comment by smrtprjcts** [comment]
As I see the firmware has changed nowadays. Maybe I have to follow its changes. If you have time now you can try with old firmware(s)

**Comment by bentolor** [comment]
It's ok. I'll stick to the new firmware as it has some features I really need/want and flashing requires some Vodoo on my side (booting Windows, etc.) Thanks for your quick feedback!

Wonder if he really changed the format of this bluetooth beacons? The new firmware also allows to use a "Mi like advertising" type. Maybe this would solve it for now?

**Comment by smrtprjcts** [comment]
I'm also doubt but don't know yet. I'll check it. You are the first who reported this but you are also the first who reported that use this firmware :)
It's a brand new thing

**Comment by smrtprjcts** [comment]
Hi.
2.3.0 is out. Please check it and i'll close the ticket if it's working

**Comment by bentolor** [comment]
@smrtprjcts Thanks for your quick reaction: It fixes the issue for me!
