### ISSUE TITLE
The ThingSpeak configuration does not work.

### ISSUE THREAD

**Issue by dupan99** [smrtprjcts/mijiatemp#26]
In the app, no configuration can be made and therefore the function can not be switched on. The parameter for channel and channel ID are not adopted. 

App version 3.3.2

Pro and ThingSpeak option was purchased.

**Comment by smrtprjcts** [comment]
Have you seen the help?
![image](https://user-images.githubusercontent.com/52231993/125765413-774e5db8-6cbe-48cf-9ac2-a1709b4de965.png)

**Comment by dupan99** [comment]
Yes I have. The menu to enter the Channel ID and Channel Write Key shows no values. And the activation brings a message that no values are entered.  Can it be that is a translation problem? I change the language to English.

**Comment by smrtprjcts** [comment]
Do you have channel id and write key?
Have you fill that? If yes fill the filelds you want to report, eg temperature. And finally enalble that.
If it's not working please send a video (to my mail) what you do..
Thanks

**Comment by dupan99** [comment]
Have solved the probeme. The error was in the input of the channel write key. Here the translation into German is wrong. The name is "Kanal Kanal".

Thanks for the quick response.

**Comment by smrtprjcts** [comment]
Good to know. I'll fix it. Thanks
Unfortunately the translate is very poor. Nobody does it.. It was made once but new texts are not updated and the olds are not fixed
